[package]
name = "zenit"
version = "0.1.0"
edition = "2021"
description = "Open-source engine replacement for Star Wars Battlefront II (2005)"
authors = ["Natalia Cholewa <natanalt@protonmail.com>"]

[dependencies]
zenit_lvl_core = { path = "../zenit_lvl_core" }
zenit_lvl = { path = "../zenit_lvl" }
zenit_proc = { path = "../zenit_proc" }
zenit_lua = { path = "../zenit_lua" }
zenit_utils = { path = "../zenit_utils" }
anyhow = "1.0.52"
thiserror = "1.0.30"
bevy = { version = "0.6.1", features = ["dynamic"] }

