[package]
name = "zenit"
version = "0.1.0"
edition = "2021"
authors = ["Natalia Cholewa <natanalt@protonmail.com>"]
description = "Open source implementation of the classic SWBF2 engine"
build = "build.rs"
links = "lua"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
winit = "0.25"
byteorder = "1.4"
lazy_static = "1.4"
libc = "0.2"
simple_logger = "1.15" # will be replaced
vulkano = "0.27"
vulkano-shaders = "0.27" # may be replaced by calling glslc from build.rs?
vulkano-win = "0.27"
#pollster = "0.2"
#wgpu = "0.11"
#spin_sleep = "1.0"
#memmap2 = "0.5"

[build-dependencies]
cc = "1.0"
bindgen = "0.59"
glob = "0.3"
