[package]
name = "zenit_lua"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
thiserror = "1.0.30"
byteorder = "1.4.3"
libc = "0.2.112"
zenit_utils = { path = "../zenit_utils", version = "0.1.0" }

[build-dependencies]
cc = "1.0.72"
bindgen = "0.59.2"
glob = "0.3"
