[package]
name = "zenit_lvl_proc"
description = "Procedural macros reexported by zenit_lvl"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
